server:
  port: 12306
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lvbin@48777742
    url: jdbc:mysql://127.0.0.1:3306/oauth2test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    druid:
      initialSize: 1
      maxActive: 20
      minIdle: 1
      maxWait: 60000
      poolPreparedStatements: true
      filters: stat,wall,slf4j
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: lvbin
        login-password: lvbin
  application:
    name: Auth-Server

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.lvbin.server

logging:
  level:
    org:
      springframework:
        security: debug
